apiVersion: v1
kind: Service
metadata:
  name: jenkins-ci-service
spec:
  type: NodePort
  selector:
    app: jenkins-ci-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30080
